year=input('输入当前年：')
month=input('输入当前月：')
date=input('输入当前日：')
print(year,month,date,sep='-')
print(year+'年'+month+'月'+date+'日')
print('{}年{}月{}日'.format(year,month,date))
print(f'{year}年{month}月{date}日')
